src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/case_comments__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>case_comments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Public__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Make Visible to External Users</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Rich_Comment__c</fullName>
        <label>Rich Comment</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <label>Case Comment</label>
    <nameField>
        <displayFormat>comment-{0000}</displayFormat>
        <label>Comment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Comments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieveNA16/classes/caseExtns.cls
public with sharing class caseExtns {

public Case newcase{get;set;}
//public String userComment{get;set;}

    public caseExtns(ApexPages.StandardController controller) {
        newCase=(Case)controller.getRecord();
        //newCOmment.comment__c='test5';
    }
public List<Case_Comments__c> getcaseComments(){
//String caseId = ApexPages.currentPage().getParameters().get('caseid');
Profile p =[select id,name from Profile where id=:userInfo.getProfileId()];
if(p.name!='community portal user clone')
return [select id,name,Comment__c,Rich_Comment__c,CreatedBy.name,CreatedDate from Case_Comments__c where case__c=:newCase.id ];
else
return [select id,name,Comment__c,Rich_Comment__c,CreatedBy.name,CreatedDate from Case_Comments__c where case__c=:newCase.id and public__c=true];
}

public void saveComment(){
    //System.debug('value is ************'+userComment);
    //String caseId = ApexPages.currentPage().getParameters().get('caseid');
    Case_Comments__c newComment = new Case_Comments__c();
    newComment.case__c=newCase.id;
    newComment.Rich_Comment__c=newCase.Comment__c;
    newComment.comment__c = newCase.Comment__c;
    insert newCOmment;
}
}
//
//