src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/case_comments__c.object
<CustomObject>
    <fields>
        <fullName>BgColor__c</fullName>
        <label>BgColor</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>case_comments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Notetype__c</fullName>
        <label>Notetype</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Rich_Comment__c</fullName>
        <label>Rich Comment</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <label>Case Comment</label>
    <nameField>
        <displayFormat>comment-{0000}</displayFormat>
        <label>Comment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Comments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieveNA16/classes/AddCommentController.cls
public  class AddCommentController{

    public AddCommentController() {

    }


    public Case newcase{get;set;}
    public id urlid;
    public String ProfileName = System.Label.Profile_Name;
    public String selectedVisibilityOption{get;set;}
    public List<SelectOption> VisibilityOptions{get;set;}
    public Boolean InternalOnlyOptions{get;set;}
    
    public AddCommentController(ApexPages.StandardController controller) {
        
        urlid = apexpages.currentpage().getparameters().get('id');
        system.debug('urlid***'+urlid);
        newCase=[select id,Comment__c from Case where id =:urlid ];
        
    }
  

    
    public PageReference saveComment(){
        User u = [select id, name, CommunityNickName from User where id=:UserInfo.getUserId() ];
        Profile p =[select id,name from Profile where id=:userInfo.getProfileId()];
        Case_Comments__c newComment = new Case_Comments__c();
        newComment.case__c=newCase.id;
        newComment.Rich_Comment__c=newCase.Comment__c;
        newComment.BgColor__c = 'background-color: #E6E6E6'; //
        newComment.Notetype__c = 'Note To Customer';
        

        insert newComment;
        return new PageReference('/'+newCase.id);
        

}
}