src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/case_comments__c.object
<CustomObject>
    <fields>
        <fullName>BgColor__c</fullName>
        <label>BgColor</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>case_comments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>NickName__c</fullName>
        <label>NickName</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Notetype__c</fullName>
        <label>Notetype</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Public__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Make Visible to External Users</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Rich_Comment__c</fullName>
        <label>Rich Comment</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <label>Case Comment</label>
    <nameField>
        <displayFormat>comment-{0000}</displayFormat>
        <label>Comment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Comments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CommentScreenController.cls
public with sharing class CommentScreenController{

    public Case newcase{get;set;}
    public Id CaseIdvalue;
    public List<Case_Comments__c> CommentRecords;
    public String ProfileName = System.Label.Profile_Name;
    public Boolean InternalColumn{get;set;}
    public Boolean ExternalColumn{get;set;}
    public Profile p;
    
    public CommentScreenController(ApexPages.StandardController controller) {
        newCase=(Case)controller.getRecord();
        system.debug('new case value'+newCase.id);
            /*p =[select id,name from Profile where id=:userInfo.getProfileId()]; */
            InternalColumn= false;
            ExternalColumn= false;
    }
    
    public List<Case_Comments__c> getcaseComments(){
 

    
    Profile p =[select id,name from Profile where id=:userInfo.getProfileId()];
        if(p.name!= ProfileName) {//'Customer Community Plus Login User Clone'
            InternalColumn = true;
            return [select id,name,Comment__c,Rich_Comment__c,CreatedBy.name,CreatedBy.FirstName,CreatedDate,BgColor__c,Notetype__c,NickName__c,Public__c from Case_Comments__c where case__c=:newCase.id ORDER BY CreatedDate DESC NULLS LAST ];
            }
        else{
            ExternalColumn = true;
            return [select id,name,Comment__c,Rich_Comment__c,CreatedBy.name,CreatedBy.FirstName,CreatedDate,BgColor__c,Notetype__c,NickName__c,Public__c from Case_Comments__c where case__c=:newCase.id and public__c=true ORDER BY CreatedDate DESC NULLS LAST];
            }
    }
}