src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Household__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is used for Seasonal Addresses Test</description>
        <label>Household</label>
        <referenceTo>Household__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Household__c.object
<CustomObject>
    <description>This is used for Seasonal Addresses Test</description>
    <label>Household</label>
    <nameField>
        <label>Household Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Households</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Seasonal_Address__c.object
<CustomObject>
    <description>This is used for Seasonal Addresses Test</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is used for Seasonal Addresses Test</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Seasonal Addresses</relationshipLabel>
        <relationshipName>Seasonal_Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Household__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is used for Seasonal Addresses Test</description>
        <label>Household</label>
        <referenceTo>Household__c</referenceTo>
        <relationshipLabel>Seasonal Addresses</relationshipLabel>
        <relationshipName>H_Seasonal_Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Seasonal Address</label>
    <nameField>
        <displayFormat>SA-{000000}</displayFormat>
        <label>Seasonal Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Seasonal Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Seasonal_Address_Line_Item__c.object
<CustomObject>
    <description>This is used for Seasonal Addresses Test</description>
    <fields>
        <fullName>Seasonal_Address__c</fullName>
        <description>This is used for Seasonal Addresses Test</description>
        <label>Seasonal Address</label>
        <referenceTo>Seasonal_Address__c</referenceTo>
        <relationshipLabel>Seasonal Address Line Items</relationshipLabel>
        <relationshipName>Seasonal_Address_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>This is used for Seasonal Addresses Test</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Seasonal Address Line Item</label>
    <nameField>
        <displayFormat>S.A.LineItem-{000000}</displayFormat>
        <label>Seasonal Address Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Seasonal Address Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

retrieveNA16/classes/Seasonal_Address_Batch_Test.cls
@isTest
public class Seasonal_Address_Batch_Test{

    static List<Household__c> hHoldsList = new List<Household__c>();
    static List<Contact> contactsList = new List<Contact>();
    static List<Seasonal_Address_Line_Item__c> lItemsList = new List<Seasonal_Address_Line_Item__c>();
    static List<Seasonal_Address__c> parentRecList = new List<Seasonal_Address__c>();
    
    public static TestMethod void getRecords(){
        //Inserting Households
        hHoldsList = seasaddrTestUtilities.gethHolds(1);
        insert hHoldsList;

        //Inserting Contacts
        contactsList = seasaddrTestUtilities.getContacts(1);
        Integer j = 0;
        for(Contact conRec: contactsList){
            conRec.Household__c = hHoldsList.get(0).id;
            j++;
        }
        insert contactsList;

        //Inserting Parent(Seasonal Address) Records
        parentRecList = seasaddrTestUtilities.getSeasAddrRecs(1);
        for(Seasonal_Address__c parentRec: parentRecList){
            parentRec.Household__c = hHoldsList.get(0).id;
            parentRec.Contact__c = contactsList.get(0).id;
        }
        insert parentRecList;

        
    }

    public static testMethod void testBatch() {
        getRecords();
        
        //Inserting Line Item records
        lItemsList = seasaddrTestUtilities.getlItems(2);
        Integer i = 0;
        for(Seasonal_Address_Line_Item__c lItemRec: lItemsList){
            lItemRec.Seasonal_Address__c = parentRecList.get(0).id;
            lItemRec.Start_Date__c = Date.today();
            i++;
        }
        insert lItemsList;

        Test.StartTest();
        Seasonal_Address_BatchClass batch = new Seasonal_Address_BatchClass();
        ID batchprocessid = Database.executeBatch(batch);
        Test.StopTest();

    }

}