src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Household__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is used for Seasonal Addresses Test</description>
        <label>Household</label>
        <referenceTo>Household__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Household__c.object
<CustomObject>
    <description>This is used for Seasonal Addresses Test</description>
    <label>Household</label>
    <nameField>
        <label>Household Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Households</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Seasonal_Address__c.object
<CustomObject>
    <description>This is used for Seasonal Addresses Test</description>
    <fields>
        <fullName>Household__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is used for Seasonal Addresses Test</description>
        <label>Household</label>
        <referenceTo>Household__c</referenceTo>
        <relationshipLabel>Seasonal Addresses</relationshipLabel>
        <relationshipName>H_Seasonal_Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Seasonal Address</label>
    <nameField>
        <displayFormat>SA-{000000}</displayFormat>
        <label>Seasonal Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Seasonal Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Seasonal_Address_Line_Item__c.object
<CustomObject>
    <description>This is used for Seasonal Addresses Test</description>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Mailing_City__c</fullName>
        <description>This is used for Seasonal Addresses Test</description>
        <label>Mailing City</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Mailing_Country__c</fullName>
        <description>This is used for Seasonal Addresses Test</description>
        <label>Mailing Country</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Mailing_Postal_Code__c</fullName>
        <label>Mailing Postal Code</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Mailing_State__c</fullName>
        <description>This is used for Seasonal Addresses Test</description>
        <label>Mailing State</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Mailing_Street__c</fullName>
        <description>This is used for Seasonal Addresses Test</description>
        <label>Mailing Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Seasonal_Address__c</fullName>
        <description>This is used for Seasonal Addresses Test</description>
        <label>Seasonal Address</label>
        <referenceTo>Seasonal_Address__c</referenceTo>
        <relationshipLabel>Seasonal Address Line Items</relationshipLabel>
        <relationshipName>Seasonal_Address_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>This is used for Seasonal Addresses Test</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>isValid_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is used for Seasonal Addresses Test</description>
        <label>Current Valid Address</label>
        <type>Checkbox</type>
    </fields>
    <label>Seasonal Address Line Item</label>
    <nameField>
        <displayFormat>S.A.LineItem-{000000}</displayFormat>
        <label>Seasonal Address Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Seasonal Address Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/seasaddrTestUtilities.cls
@isTest
public class seasaddrTestUtilities{

    public static List<Contact> getContacts(integer noOfContacts){

        List<Contact> conRecList = new List<Contact>();
        for(Integer i=1; i<=noOfContacts; i++){
            Contact conRec = new Contact(
                LastName='FC3S'+i,
                Email = 'ryo@redsuns.com'
            );
            conRecList.add(conRec);
        }
        return conRecList;
    }

    public static List<Household__c> gethHolds(integer noOfhHolds){

        List<Household__c> hHoldRecList = new List<Household__c>();
        for(Integer i=1; i<=noOfhHolds; i++){
            Household__c hHoldRec = new Household__c(
                Name='Straw Hat'+i
            );
            hHoldRecList.add(hHoldRec);
        }
        return hHoldRecList;
    }

    public static List<Seasonal_Address_Line_Item__c> getlItems(integer noOflItems){

        List<Seasonal_Address_Line_Item__c> lItemRecList = new List<Seasonal_Address_Line_Item__c>();
        for(Integer i=1; i<=noOflItems; i++){
            Integer j = i+3;
            Seasonal_Address_Line_Item__c lItemRec = new Seasonal_Address_Line_Item__c(
                isValid_Address__c=false,
                End_Date__c = Date.today().addDays(+j),
                Start_Date__c = Date.today().addDays(+i),
                Mailing_Street__c = 'test'+i,
                Mailing_State__c = 'test'+i,
                Mailing_Postal_Code__c = '94501',
                Mailing_Country__c = 'test'+i,
                Mailing_City__c = 'test'+i
            );
            lItemRecList.add(lItemRec);
        }
        return lItemRecList;
    }

    public static List<Seasonal_Address__c> getSeasAddrRecs(integer noOfSeasAdresses){

        List<Seasonal_Address__c> seasAddrRecList = new List<Seasonal_Address__c>();
        for(Integer i=1; i<=noOfSeasAdresses; i++){
            Seasonal_Address__c seasAddrRec = new Seasonal_Address__c(
                
            );
            seasAddrRecList.add(seasAddrRec);
        }
        return seasAddrRecList;
    }

}