src/objects/Example_Trigger_Executions__c.object
<CustomObject>
    <description>This is an object for Trigger Executions Examples</description>
    <label>Trigger Executions Example</label>
    <nameField>
        <label>Trigger Executions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trigger Executions Examples</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SI_Trigger_Executions__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom Setting to control trigger executions for each funcationality</description>
    <fields>
        <fullName>SI_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Switch to control the execution of the trigger</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Trigger Executions</label>
</CustomObject>

retrieveNA16/classes/Example_Trigger_Executions_Dispatcher.cls
public class Example_Trigger_Executions_Dispatcher{
    
    public static void beforeMethod(List<Example_Trigger_Executions__c> oldList, List<Example_Trigger_Executions__c> newList, Map<Id,Example_Trigger_Executions__c> oldMap,Map<Id,Example_Trigger_Executions__c> newMap){
        if(trigger.isInsert){
            // Fetching "Custom Setting" containing details to trigger switch on/off
            Map <String, SI_Trigger_Executions__c> triggerExecutionsMap = SI_Trigger_Executions__c.getAll();
            if (!triggerExecutionsMap.isEmpty()){
                if (triggerExecutionsMap.containsKey('BeforeInsertTriggerExecutions') && triggerExecutionsMap.get('BeforeInsertTriggerExecutions').SI_Active__c){ 
                    Example_Trigger_Executions_Handler.Example_Method(newList);
                    
                }
            }
            
        }
        if(trigger.isUpdate){

        }
        if(trigger.isDelete){
            
        }
    } 

    public static void afterMethod(List<Example_Trigger_Executions__c> oldList, List<Example_Trigger_Executions__c> newList, Map<Id,Example_Trigger_Executions__c> oldMap,Map<Id,Example_Trigger_Executions__c> newMap){
        if(trigger.isInsert){
            // Fetching "Custom Setting" containing details to trigger switch on/off
            Map <String, SI_Trigger_Executions__c> triggerExecutionsMap = SI_Trigger_Executions__c.getAll();
            if (!triggerExecutionsMap.isEmpty()){
                if (triggerExecutionsMap.containsKey('AfterInsertTriggerExecutions') && triggerExecutionsMap.get('AfterInsertTriggerExecutions').SI_Active__c){ 
                    Example_Trigger_Executions_Handler.Example_Method2(newList);
                    
                }
            }
            
        }
        if(trigger.isUpdate){

        }
        if(trigger.isDelete){
            
        }
    }
    
    
    
}