src/objects/Example_Trigger_Executions__c.object
<CustomObject>
    <description>This is an object for Trigger Executions Examples</description>
    <label>Trigger Executions Example</label>
    <nameField>
        <label>Trigger Executions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trigger Executions Examples</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SI_Trigger_Executions__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom Setting to control trigger executions for each funcationality</description>
    <fields>
        <fullName>SI_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Switch to control the execution of the trigger</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SI_Class_Name__c</fullName>
        <description>Name of the class that handles the logic for the trigger</description>
        <label>Class Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SI_Description__c</fullName>
        <description>Description of the custom setting record</description>
        <label>Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SI_Object__c</fullName>
        <description>API name of the object that is being controller by the trigger</description>
        <label>Object</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SI_Trigger_Events__c</fullName>
        <description>Events that trigger transaction logic for this functionality</description>
        <label>Trigger Events</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>Trigger Executions</label>
</CustomObject>

retrieveNA16/classes/Example_Trigger_Executions_Test.cls
/*@isTest
public class Example_Trigger_Executions_Test{

    public static testmethod void Example_Method(){
        //Create Custom Settings
        SI_Trigger_Executions__c TriggerExecution = new SI_Trigger_Executions__c ();
        TriggerExecution.Name = 'BeforeInsertTriggerExecutions';
        TriggerExecution.SI_Active__c = true;
        TriggerExecution.SI_Class_Name__c ='Example_Trigger_Executions_Handler';
        TriggerExecution.SI_Description__c = 'MethodDescription';
        TriggerExecution.SI_Object__c = 'Trigger Executions Example';
        TriggerExecution.SI_Trigger_Events__c = 'Before Insert';
        insert TriggerExecution;
        System.assert(TriggerExecution.id!= null, 'Record not created');
        List<Example_Trigger_Executions__c> TrgExecList =  new List<Example_Trigger_Executions__c>();
        TrgExecList = TestUtilities.getTriggerExecutions(3);
        insert TrgExecList; 
    }
    
    public static testmethod void Example_Method2(){
        //Create Custom Settings
        SI_Trigger_Executions__c TriggerExecution = new SI_Trigger_Executions__c();
        TriggerExecution.Name = 'AfterInsertTriggerExecutions';
        TriggerExecution.SI_Active__c = true;
        TriggerExecution.SI_Class_Name__c ='Example_Trigger_Executions_Handler';
        TriggerExecution.SI_Description__c = 'MethodDescription';
        TriggerExecution.SI_Object__c = 'Trigger Executions Example';
        TriggerExecution.SI_Trigger_Events__c = 'After Insert';
        insert TriggerExecution;
        List<Example_Trigger_Executions__c> TrgExecList =  new List<Example_Trigger_Executions__c>();
        TrgExecList = TestUtilities.getTriggerExecutions(3);
        insert TrgExecList; 
    
    }
}*/

@isTest
public class Example_Trigger_Executions_Test{

    public static testmethod void Example_Method(){

        //Create Custom Settings
        SI_Trigger_Executions__c TriggerExecution = new SI_Trigger_Executions__c (
            Name = 'BeforeInsertTriggerExecutions',
            SI_Active__c = true,
            SI_Class_Name__c = 'Example_Trigger_Executions_Handler',
            SI_Description__c = 'MethodDescription',
            SI_Object__c  ='Trigger Executions Example',
            SI_Trigger_Events__c = 'Before Insert'
        );
        insert TriggerExecution;
        System.assert(TriggerExecution.id!= null, 'Record not created');
        
        List<Example_Trigger_Executions__c> TrgExecList =  new List<Example_Trigger_Executions__c>();
            TrgExecList = TestUtilities.getTriggerExecutions(3);
            insert TrgExecList; 
    }
    
    public static testmethod void Example_Method2(){
        //Create Custom Settings
        SI_Trigger_Executions__c TriggerExecution = new SI_Trigger_Executions__c (
            Name = 'AfterInsertTriggerExecutions',
            SI_Active__c = true,
            SI_Class_Name__c = 'Example_Trigger_Executions_Handler',
            SI_Description__c = 'MethodDescription',
            SI_Object__c  ='Trigger Executions Example',
            SI_Trigger_Events__c = 'After Insert'
        );
        insert TriggerExecution;
        
        List<Example_Trigger_Executions__c> TrgExecList =  new List<Example_Trigger_Executions__c>();
        TrgExecList = TestUtilities.getTriggerExecutions(3);
        insert TrgExecList; 
    
    }
}